<script setup>
import { RouterView } from 'vue-router';
import Header from '@/components/header/index.vue';
</script>

<template>
  <header>
    <div class="wrapper">
      <Header/>
      <RouterView/>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>      
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>      
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>      
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>      
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
      <p>f</p>
    </div>
  </header>

  <main>
    <TheWelcome />
  </main>
</template>

<style scoped>
</style>
